# Generated by Django 4.0.6 on 2022-08-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_gender_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures/%d/%m/%y', verbose_name='Profile Picture:'),
        ),
    ]
