# Generated by Django 4.0.6 on 2022-08-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%y/%m/%d', verbose_name='Profile Picture:'),
        ),
    ]
