# Generated by Django 4.0.6 on 2022-08-12 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waste Location:')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WasteLocation',
                'verbose_name_plural': 'WasteLocations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waste Type:')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WasteType',
                'verbose_name_plural': 'WasteTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WasteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_title', models.CharField(default='Waste Payment Plan', max_length=255, verbose_name='Setting Title:')),
                ('dues', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount Payable:')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_setting', to='waste.wastelocation')),
                ('waste_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_type_setting', to='waste.wastetype')),
            ],
            options={
                'verbose_name': 'WasteSetting',
                'verbose_name_plural': 'WasteSettings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DustBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bin Label:')),
                ('digital_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digital Address:')),
                ('gps_latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gps Latitude:')),
                ('gps_longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gps Longitude:')),
                ('bin_ready', models.BooleanField(default=False)),
                ('bin_collected', models.BooleanField(default=False)),
                ('payment_made', models.BooleanField(default=False)),
                ('bin_returned', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_dustbins', to='waste.wastelocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_waste_locations', to=settings.AUTH_USER_MODEL)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_types', to='waste.wastetype')),
            ],
            options={
                'verbose_name': 'Dustbin',
                'verbose_name_plural': 'Dustbins',
                'managed': True,
            },
        ),
    ]
