# Generated by Django 4.0.6 on 2022-08-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dustbin',
            old_name='bin_returned',
            new_name='empty_bin',
        ),
    ]
