# Generated by Django 4.0.6 on 2022-08-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_rename_bin_returned_dustbin_empty_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbin',
            name='empty_bin',
            field=models.BooleanField(default=True),
        ),
    ]
