# Generated by Django 4.0.6 on 2022-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_dustbin_empty_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelocation',
            name='digital_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Digital Address:'),
        ),
        migrations.AddField(
            model_name='wastelocation',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gps Latitude:'),
        ),
        migrations.AddField(
            model_name='wastelocation',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gps Longitude:'),
        ),
    ]
