# Generated by Django 4.0.6 on 2022-08-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0004_wastelocation_digital_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastesettings',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_setting', to='waste.wastelocation'),
        ),
        migrations.AlterField(
            model_name='wastesettings',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_type_setting', to='waste.wastetype'),
        ),
        migrations.CreateModel(
            name='WasteDisposalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmation', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='waste_payments', to='waste.wastesettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
