# Generated by Django 4.0.6 on 2022-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_alter_wastesettings_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='payment_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
